name: Temperatura Diària

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  actualitzar_temperatura:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script
        run: python apy_request.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commitejar i pujar el fitxer JSON
        run: |
          git add temp_*.json
          git commit -m "Afegir temperatura diària per a $(date +'%Y-%m-%d')" || echo "Sense canvis"
          git push
